package litebans;

public static interface lG {
    public static final int a;
    public static final int an;
    public static final int j;
    public static final int b;
    public static final int ac;
    public static final int J;
    public static final int q;
    public static final int z;
    public static final int Z;
    public static final long aa;
    public static final int y;
    public static final int r;
    public static final int ah;
    public static final long O;
    public static final int H;
    public static final int i;
    public static final int K;
    public static final int n;
    public static final int x;
    public static final int M;
    public static final int F;
    public static final int E;
    public static final int o;
    public static final int B;
    public static final int f;
    public static final int U;
    public static final int d;
    public static final int W;
    public static final int m;
    public static final int L;
    public static final int G;
    public static final int N;
    public static final int am;
    public static final int V;
    public static final int C;
    public static final int T;
    public static final int v;
    public static final byte ad;
    public static final byte al;
    public static final byte aj;
    public static final byte R;
    public static final byte ag;
    public static final byte c;
    public static final byte h;
    public static final byte l;
    public static final byte w;
    public static final byte k;
    public static final byte X;
    public static final byte s;
    public static final byte g;
    public static final byte I;
    public static final byte Y;
    public static final String af;
    public static final String A;
    public static final String p;
    public static final String u;
    public static final String t;
    public static final String D;
    public static final String P;
    public static final String ae;
    public static final String ak;
    public static final int Q;
    public static final int ab;
    public static final int S;
    public static final int ai;
    public static final int e;

    static {
        e = 12;
        ai = 12;
        S = 131;
        ab = 4;
        Q = 508;
        ak = "tar\u0000";
        ae = "././@LongLink";
        P = "\u0000\u0000";
        D = "ustar\u0000";
        t = "0\u0000";
        u = " \u0000";
        p = "ustar ";
        A = "00";
        af = "ustar\u0000";
        Y = (byte)103;
        I = (byte)88;
        g = (byte)120;
        s = (byte)83;
        X = (byte)76;
        k = (byte)75;
        w = (byte)55;
        l = (byte)54;
        h = (byte)53;
        c = (byte)52;
        ag = (byte)51;
        R = (byte)50;
        aj = (byte)49;
        al = (byte)48;
        ad = 0;
        v = 1;
        T = 504;
        C = 21;
        V = 4;
        am = 12;
        N = 12;
        G = 12;
        L = 1;
        m = 96;
        W = 1;
        d = 4;
        U = 12;
        f = 12;
        B = 12;
        o = 155;
        E = 8;
        F = 32;
        M = 32;
        x = 12;
        n = 2;
        K = 263;
        i = 6;
        H = 257;
        O = 0x1FFFFFFFFL;
        ah = 12;
        r = 148;
        y = 8;
        aa = 0x1FFFFFL;
        Z = 8;
        z = 8;
        q = 8;
        J = 100;
        ac = 4;
        b = 3;
        j = 2;
        an = 10240;
        a = 512;
    }
}

