package litebans;

public interface LiteBansModule_413 {
    public static final int BaseCoreGenericHandler;
    public static final int HikariDataSource;
    public static final int GnuSparseMapHandler;
    public static final int LiteBansModule_31;
    public static final int ac;
    public static final int J;
    public static final int q;
    public static final int z;
    public static final int NullHandler_8;
    public static final long aa;
    public static final int HoverTextFormatter;
    public static final int r;
    public static final int ah;
    public static final long O;
    public static final int H;
    public static final int i;
    public static final int K;
    public static final int n;
    public static final int LiteBansModule_435;
    public static final int PlayerQuitListener;
    public static final int F;
    public static final int PunishmentService;
    public static final int BroadcastService;
    public static final int B;
    public static final int LiteBansModule_195;
    public static final int U;
    public static final int AsyncBackgroundTask_5;
    public static final int W;
    public static final int m;
    public static final int L;
    public static final int BanHandler_4;
    public static final int LiteBansModule_432;
    public static final int MessageKey;
    public static final int V;
    public static final int BanHandler_2;
    public static final int T;
    public static final int CommandThrottleService;
    public static final byte ad;
    public static final byte LiteBansModule_17;
    public static final byte aj;
    public static final byte LockdownService;
    public static final byte LiteBansModule_12;
    public static final byte c;
    public static final byte LiteBansModule_241;
    public static final byte LiteBansModule_403;
    public static final byte DatabaseMonitorService;
    public static final byte Utf8Handler_2;
    public static final byte X;
    public static final byte AsyncBackgroundTask_21;
    public static final byte g;
    public static final byte BanHandler_5;
    public static final byte Y;
    public static final String af;
    public static final String A;
    public static final String PunishmentTableService;
    public static final String ServerSyncService;
    public static final String AsyncBackgroundTask_22;
    public static final String D;
    public static final String P;
    public static final String LiteBansModule_10;
    public static final String ak;
    public static final int PluginHookService;
    public static final int ab;
    public static final int S;
    public static final int ai;
    public static final int e;

    static {
        e = 12;
        ai = 12;
        S = 131;
        ab = 4;
        PluginHookService = 508;
        ak = "tar\u0000";
        LiteBansModule_10 = "././@LongLink";
        P = "\u0000\u0000";
        D = "ustar\u0000";
        AsyncBackgroundTask_22 = "0\u0000";
        ServerSyncService = " \u0000";
        PunishmentTableService = "ustar ";
        A = "00";
        af = "ustar\u0000";
        Y = (byte)103;
        BanHandler_5 = (byte)88;
        g = (byte)120;
        AsyncBackgroundTask_21 = (byte)83;
        X = (byte)76;
        Utf8Handler_2 = (byte)75;
        DatabaseMonitorService = (byte)55;
        LiteBansModule_403 = (byte)54;
        LiteBansModule_241 = (byte)53;
        c = (byte)52;
        LiteBansModule_12 = (byte)51;
        LockdownService = (byte)50;
        aj = (byte)49;
        LiteBansModule_17 = (byte)48;
        ad = 0;
        CommandThrottleService = 1;
        T = 504;
        BanHandler_2 = 21;
        V = 4;
        MessageKey = 12;
        LiteBansModule_432 = 12;
        BanHandler_4 = 12;
        L = 1;
        m = 96;
        W = 1;
        AsyncBackgroundTask_5 = 4;
        U = 12;
        LiteBansModule_195 = 12;
        B = 12;
        BroadcastService = 155;
        PunishmentService = 8;
        F = 32;
        PlayerQuitListener = 32;
        LiteBansModule_435 = 12;
        n = 2;
        K = 263;
        i = 6;
        H = 257;
        O = 0x1FFFFFFFFL;
        ah = 12;
        r = 148;
        HoverTextFormatter = 8;
        aa = 0x1FFFFFL;
        NullHandler_8 = 8;
        z = 8;
        q = 8;
        J = 100;
        ac = 4;
        LiteBansModule_31 = 3;
        GnuSparseMapHandler = 2;
        HikariDataSource = 10240;
        BaseCoreGenericHandler = 512;
    }
}

